#!/bin/sh
#=====================================| VARIAVEIS GLOBAIS
export version='1.0'
export pkgext='tpkg' # Extensão do pacote

# DESABILITANDO SUPORTE A UNICODE
# PARA MELHOR PERFORMANCE.
export LC_ALL=C
export LANG=C

#=====================================| FUNÇÕES
CHECK_PKG() {
   pkg_name="$@"

   # Verificando o extensão do pacote. Precisa ser tpkg.
   if ! echo "$pkg_name" | grep "\b${pkgext}\b$"; then
      printf '%s\n' "O formato do pacote deve ser: ${pkgext}"
      return 1
   fi

   # Verificando se tem espaços no nome do pacote.
   if echo "$pkg_name" | grep -qE "[[:space:]]+"; then
      printf '%s\n' "Não utilize ESPAÇOS no nome do pacote."
      printf '%s\n' "Abortando a criação do pacote."
      return 1
   fi

   # Verificando quantos traços existem.
   # O traço (-) é um delitimitador, precisa ter 2.
   # formato: nomedopacote-versão-build.tpkg
   verify=$(echo "${pkg_name}" | grep -o "-" | wc -l)
   if [ "$verify" -lt '2' ] || [ "$verify" -gt '2' ]; then
      printf '%s\n' "Erro... O formato do pacote deve ser o seguinte:"
      printf '%s\n' "NomeDoPacote-Versão-Build.${pkgext}"
      return 1
   fi

   return 0
}

# Criação do pacote.
CREATE_PKG() {
   pkg_name="$1" # Recebendo nome do pacote.

   if [ "$VERBOSE" = '1' ]; then
      if tar -cvf ../${pkg_name} .; then
         printf '%s\n' "O pacote foi criado em ../${pkg_name}"
      else
         printf '%s\n' "O pacote ${pkg_name} não foi criado..."
         exit 1
      fi
   else
      if tar -cf ../${pkg_name} .; then
         printf '%s\n' "O pacote foi criado em ../${pkg_name}"
         return 0
      else
         printf '%s\n' "O pacote ${pkg_name} não foi criado..."
         exit 1
      fi
   fi
}

USAGE() {
   cat <<EOF
createpkg - OPÇÕES

   create, -c
      Cria um pacote .tpkg. Precisa estar dentro do diretório
      principal do pacote para ser gerado. O mesmo será criado
      um diretório acima.

   verbose, -v

AUTOR  : Jefferson 'Slackjeff' Carneiro
CONTATO: jeffersoncarneiro@slackjeff.com.br
EOF
}

#====================================| TESTE

# Se nulo, vai para o help.
if [ -z "$1" ]; then
   USAGE
fi

# PARSER
while [ -n "$1" ]; do
   case "$1" in
      create|-c)
         CMD=$1
         shift
      ;;

      verbose|-v)
         VERBOSE=1 # 0 OFF / 1 ON
         shift
      ;;

      *.tpkg)
         PKG=$1
         shift
      ;;

      *)
         USAGE
         exit 1
      ;;
   esac
done


#=====================================| INICIO
case "$CMD" in
   create|-c)
      # Sem nome do pacote? Então sai...
      if [ -z "$CMD" ]; then
         printf '%s\n' "Você precisa fornecer um nome de pacote."
         exit 1
      fi
      CHECK_PKG "$PKG" || exit 1 # Checagem do pacote.
      CREATE_PKG "$PKG" # Chamando função para criar o pacote.
   ;;
esac